services:
  rails:
    image: burrnboy/agentflows:v1
    depends_on:
      - postgres
      - redis
    environment:
      RAILS_ENV: production
      NODE_ENV: production
      INSTALLATION_ENV: docker

      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: chatwoot
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: yourpassword

      REDIS_URL: redis://redis:6379

      SECRET_KEY_BASE: 0dfcb7480f2368a33aef3db4851f85cd5f610dea04bf0dcc656127c0d78eaf1ef32d06f15fb5f23abab39367f1bcaaaf0957fcd1ebe9791d5e84387092565756

    volumes:
      - storage_data:/app/storage

    expose:
      - "3000"

    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]

    restart: always

  sidekiq:
    image: burrnboy/agentflows:v1
    depends_on:
      - postgres
      - redis
    environment:
      RAILS_ENV: production
      NODE_ENV: production
      INSTALLATION_ENV: docker

      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: chatwoot
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: yourpassword

      REDIS_URL: redis://redis:6379

      SECRET_KEY_BASE: b257b5d7d53884e28c5497f09492df573614781494df4455fba2500f52cca49fe354d6a8b3bc8b27d5f6246ca7b8d76079ebb2d0fc928edd053f2316ae462e03

    volumes:
      - storage_data:/app/storage

    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]

    restart: always

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chatwoot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword

  redis:
    image: redis:alpine
    restart: always
    command: redis-server
    volumes:
      - redis_data:/data

volumes:
  storage_data:
  postgres_data:
  redis_data:
